### ISSUE TITLE
Generate debug video Example doesn't run

### ISSUE THREAD

**Issue by gdavila** [leandromoreira/digital_video_introduction#100]
I'm triying to run the example provided in [debug video Example ](https://github.com/leandromoreira/digital_video_introduction/blob/master/encoding_pratical_examples.md#generate-debug-video) to generate a debug video with macro blocks. But I get the next error:

```[NULL @ 0x9219c0] [Eval @ 0x7ffd11e97290] Undefined constant or missing '(' in 'vis_mb_type'
[NULL @ 0x9219c0] Unable to parse option value "vis_mb_type"
[NULL @ 0x9219c0] Error setting option debug to value vis_mb_type.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x91ff80] Failed to open codec in avformat_find_stream_info
[NULL @ 0x922d40] [Eval @ 0x7ffd11e97290] Undefined constant or missing '(' in 'vis_mb_type'
[NULL @ 0x922d40] Unable to parse option value "vis_mb_type"
[NULL @ 0x922d40] Error setting option debug to value vis_mb_type.
```
The image that docker runs from `jrottenberg/ffmpeg` contanis:
```
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
```

**Comment by leandromoreira** [comment]
Hey @gdavila how is goin'?

I think you're facing this error due to the fact that `vis_mb_type` is only supported by 10/17 FFmpeg's release.

> The following sections apply to ffmpeg versions older than October 21 2017.

**Comment by gdavila** [comment]
Thanks @leandromoreira. I suspected it, but given that any ffmpeg version/tag was specified on the docker cmd, I was not sure. Maybe the docker cmd in [s/ffmpeg](https://github.com/leandromoreira/digital_video_introduction/blob/master/s/ffmpeg) file should point to the image where this feature is supported.

**Comment by leandromoreira** [comment]
Totally @gdavila =/ I'll let this open so when I have a free time or anybody else can do a PR to solve this.

**Comment by gdavila** [comment]
I've added the right tag to the ffmpeg Docker Image and send a [PR](https://github.com/leandromoreira/digital_video_introduction/pull/101) . As far as I could check, the PR  shouldn't affect the rest of the provided examples.

**Comment by leandromoreira** [comment]
thank you very much, I merged
