### ISSUE TITLE
Possible mistake with H.264 profile 

### ISSUE THREAD

**Issue by vonorfasyexela** [leandromoreira/digital_video_introduction#102]
In the 6th step of "A generic codec" you have the following line:

> The second byte (binary=01100100, hex=0x64, dec=100) of an SPS NAL is the field profile_idc which shows the profile that the encoder has used, in this case, we used the **constrained high-profile**, it's a high profile without the support of B (bi-predictive) slices. 

Maybe it should be just "high profile"? Because the next byte is 0x00 and this next byte determines the actual type of High Profile (constrained or progressive). And if this byte is 0x00 then I guess it is just High Profile.

Please fix me if I'm wrong.

**Comment by leandromoreira** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/55913/89587545-31878080-d818-11ea-8fec-0bfe4c67104f.png">
I think you're right :)
