### ISSUE TITLE
Needed more descriptive steps for running Jupyter example

### ISSUE THREAD

**Issue by naveenv05** [leandromoreira/digital_video_introduction#106]
I was trying to execute the hands-on example below,
**https://github.com/leandromoreira/digital_video_introduction#hands-on-play-around-with-image-and-color**

Following is the output that i got,

> Executing the command: jupyter notebook
> [I 15:14:55.718 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
> [I 15:14:56.435 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.8/site-packages/jupyterlab
> [I 15:14:56.436 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
> [I 15:14:56.438 NotebookApp] Serving notebooks from local directory: /home/jovyan
> [I 15:14:56.438 NotebookApp] Jupyter Notebook 6.1.3 is running at:
> [I 15:14:56.439 NotebookApp] http://da8379b349f0:8888/?token=fd62f89f08afd54b0b9f00a83288009de18d0d4e8775221d
> [I 15:14:56.439 NotebookApp]  or http://127.0.0.1:8888/?token=fd62f89f08afd54b0b9f00a83288009de18d0d4e8775221d
> [I 15:14:56.439 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [C 15:14:56.442 NotebookApp] 

    
>    To access the notebook, open this file in a browser:
>         file:///home/jovyan/.local/share/jupyter/runtime/nbserver-6-open.html
>     Or copy and paste one of these URLs:
>         http://da8379b349f0:8888/?token=fd62f89f08afd54b0b9f00a83288009de18d0d4e8775221d
>      or http://127.0.0.1:8888/?token=fd62f89f08afd54b0b9f00a83288009de18d0d4e8775221d

Of the above, only the URL http://127.0.0.1:8888/?token=fd62f89f08afd54b0b9f00a83288009de18d0d4e8775221d  was working for me.

Below is the snapshot of the URL that is loaded from my browser,
[
![Jupyter-Notebook](https://user-images.githubusercontent.com/34655543/93786516-42cbf700-fbe4-11ea-9145-c3be48a91232.png)
](url) 

I am unable to proceed further as to how to execute the 'ipython' script for the hands-on task ( **do not find the ipython script loaded in the URL tab**). **Any further inputs on how to run a sample jupyter notebook hands-on exercise would be helpful. (Yes, I did read the section on "How to use jupyter")**

Thank you

**Comment by leandromoreira** [comment]
Hi there @naveenv05 how are you? =)

I think you run `./start_jupyter.sh` within the `s` folder while you should instead run this command from the root of the project `./s/start_jupyter.sh`.

I tried to do exactly what I'm describing to you I could see the http://127.0.0.1:8888/notebooks/work/image_as_3d_array.ipynb working.


```bash
cd /tmp
git clone --depth 1 https://github.com/leandromoreira/digital_video_introduction.git
cd digital_video_introduction
./s/start_jupyter.sh
```

**Comment by naveenv05** [comment]
Hi @leandromoreira  . Thanks much. When I executed from the root folder I am now finding the ipython file.
