### ISSUE TITLE
/files/v/bunny_1080p_60fps.mp4: No such file or directory

### ISSUE THREAD

**Issue by meeme9** [leandromoreira/digital_video_introduction#111]
setup.sh calls s/cut_smaller_video.sh
while the file uri in s/cut_smaller_video.sh is strange, it starts with '/file'

**Comment by leandromoreira** [comment]
@meeme9 thanks for the heads up, as for the strange path, that's because we're using [dockerized ffmpeg](https://github.com/leandromoreira/digital_video_introduction/blob/master/s/ffmpeg) which "mounts" your current directory into the "/files/" folder on the container.

```bash
docker run --rm -v $(pwd):/files jrottenberg/ffmpeg:3.3 $@
```

**Comment by leandromoreira** [comment]
by the way, I removed the download and cut since the original file isn't available do download and we stored, at v/ directory, the small version of the video.

**Comment by leandromoreira** [comment]
I'll let it opened, and if you think that my solution (just to ignore the "cut") and my explanation (about the why of /files) are good enough feel free to close it. =) once again, thanks.

**Comment by meeme9** [comment]
Thanks for your work!
It's OK on my machine now.
