### ISSUE TITLE
I suggest specifying tag of docker image  `jupyter/scipy-notebook` because `scipy.misc.bytescale` method does not exists.

### ISSUE THREAD

**Issue by yuji38kwmt** [leandromoreira/digital_video_introduction#115]
`scipy.misc.bytescale` method does not exists in `jupyter/scipy-notebook` docker image.

https://github.com/leandromoreira/digital_video_introduction/blob/master/uniform_quantization_experience.ipynb

```
import numpy as np
import matplotlib.pyplot as plt
from scipy import fftpack
from scipy.misc import bytescale
import matplotlib.image as mpimg
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-17733afde104> in <module>
      2 import matplotlib.pyplot as plt
      3 from scipy import fftpack
----> 4 from scipy.misc import bytescale
      5 import matplotlib.image as mpimg
ImportError: cannot import name 'bytescale' from 'scipy.misc' (/opt/conda/lib/python3.8/site-packages/scipy/misc/__init__.py)
```

* python 3.8.8
* scipy 1.6.3

I suggest specifying tag of docker image  `jupyter/scipy-notebook`.
https://github.com/leandromoreira/digital_video_introduction/blob/master/s/start_jupyter.sh

**Comment by leandromoreira** [comment]
Thanks @yuji38kwmt you're right , also feel free to send a PR :)

**Comment by yuji38kwmt** [comment]
@leandromoreira I created PR.
https://github.com/leandromoreira/digital_video_introduction/pull/117
