### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by emilsas** [leandromoreira/digital_video_introduction#138]
Hey guys!
I will start translating this document to Spanish to enable more people learning video!

It is awesome all the work done here @leandromoreira.

Cheers!

**Comment by leandromoreira** [comment]
Thank you @emilsas I appreciate it!

**Comment by emilsas** [comment]
Anyone can check my progress here:

https://github.com/emilsas/digital_video_introduction/tree/138-add-spanish-translation

**Comment by emilsas** [comment]
Closed by #140
