### ISSUE TITLE
 Converting between YCbCr and RGB

### ISSUE THREAD

**Issue by LogX7** [leandromoreira/digital_video_introduction#26]
> Converting between YCbCr and RGB
> 
> Some may argue, how can we produce all the colors without using the green?
> 
> To answer this question we'll walk through a conversion from RGB to YCbCr. We'll use the coefficients from the standard BT.601 that was recommended by the group ITU-R* . The first step is to calculate the luma, we'll use the constants suggested by ITU and replace the RGB values.
> 
> Y = 0.299R + 0.587G + 0.114B
> 
> Once we had the luma, we can split the colors (chroma blue and red):
> 
> Cb = 0.564(B - Y)
> Cr = 0.713(R - Y)
> 
> And we can also convert it back and even get the green by using YCbCr.
> 
> R = Y + 1.402Cr
> B = Y + 1.772Cb
> G = Y - 0.344Cb - 0.714Cr

is this done for each pixel ?

and i didn't understand how did you use the diagram to get the Y = R + G + B  values.. and where did you get the constants from 
can you give an example ?

**Comment by leandromoreira** [comment]
> is this done for each pixel?

> ... constants ?

These coefficients varies from standard to standard, for instance, we're using [BT.601 (ITU-R)](https://en.wikipedia.org/wiki/Rec._601)

**Comment by LogX7** [comment]
thank you !
are the R' G' B' which are multiplied by the coefficients the same as the 3 points making the triangle that is representing the color in the diagram ?
