### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by jasdeepsingh** [leandromoreira/digital_video_introduction#27]
Just wanted to leave a thank you note that I've been meaning to learn about codecs & related video 
technologies for so long, but always felt intimidated by the terminology and complexity. 

Your project on Github made it really approachable and to the point! Waiting for the sections on Online Streaming - That's what i really want to focus on as my background is in Web Development.

Thank you once again for putting together such great material!

**Comment by Utopiah** [comment]
Indeed thanks a lot, really well done, can't wait for the online streaming part! :D
