### ISSUE TITLE
Source return 404: https://www.iem.thm.de/telekom-labor/zinke/mk/mpeg2beg/whatisit.htm

### ISSUE THREAD

**Issue by ArchimboldiMao** [leandromoreira/digital_video_introduction#43]
In README.md, there is a source of graph shows how the first and second coefficient is calculated, using weights which are unique for each index.
But the Source : https://www.iem.thm.de/telekom-labor/zinke/mk/mpeg2beg/whatisit.htm  return 404.

**Comment by leandromoreira** [comment]
Thank you @ArchimboldiMao it was working but you can still access through here https://web.archive.org/web/20150129171151/https://www.iem.thm.de/telekom-labor/zinke/mk/mpeg2beg/whatisit.htm
