### ISSUE TITLE
It seems that most of the links are broken

### ISSUE THREAD

**Issue by peterlitvak** [leandromoreira/digital_video_introduction#44]
There are a lot of links in the text that point to:
https://github.com/leandromoreira/digital_video_introduction/blob/master/... seems like the notebook links are mostly working but the other ones are not

**Comment by leandromoreira** [comment]
Hi @peterlitvak can you list some of them?

**Comment by peterlitvak** [comment]
Yes, sorry, I think all that point to https://github.com/leandromoreira/introduction_video_technology/blob/master/enconding_pratical_examples.md are broken because the enconding_pratical_examples.md is not there maybe?

**Comment by leandromoreira** [comment]
ohh yeah, we =( rename this file my bad.

**Comment by leandromoreira** [comment]
thank you very much @peterlitvak  🍻

**Comment by peterlitvak** [comment]
👍
