### ISSUE TITLE
Should the End of stream's NAL type id is 11, not 12?

### ISSUE THREAD

**Issue by ArchimboldiMao** [leandromoreira/digital_video_introduction#45]
Should the End of stream's NAL type id is 11, not 12?

<img width="491" alt="end_of_stream" src="https://user-images.githubusercontent.com/6983215/27523949-87311108-5a63-11e7-9b13-42535dce46b1.png">

**Comment by leandromoreira** [comment]
You're right, my bad, I looked at http://www.itu.int/rec/T-REC-H.264-201610-I and saw it's in fact 11.

![screen shot 2017-06-26 at 8 08 58 am](https://user-images.githubusercontent.com/55913/27536738-d7852080-5a46-11e7-836c-15e140e3d217.png)
