### ISSUE TITLE
luigi is a color channel?

### ISSUE THREAD

**Issue by bjorn3** [leandromoreira/digital_video_introduction#86]
![](https://github.com/leandromoreira/digital_video_introduction/raw/cd169e40ae05bd9a4ba65b692eb2d6b77d4a4e90/i/rgb_channels_intensity.png)

It should have been called green instead of luigi.

**Comment by leandromoreira** [comment]
Hey @bjorn3 this was supposed to be a joke. 😜  since **Mario is red** then **Luigi might be the green channel**.

![image](https://user-images.githubusercontent.com/55913/69478244-221def80-0dcf-11ea-8bb7-106b70a91c22.png)

**Comment by bjorn3** [comment]
:)
