### ISSUE TITLE
P-Frame section - Typo?

### ISSUE THREAD

**Issue by nsesh** [leandromoreira/digital_video_introduction#94]
In P-Frame section, it is mentioned "**We can rebuild frame 1, only using the difference and referencing to the previous frame**". Shouldn't it be "frame 2"?

Kindly correct me.

**Comment by leandromoreira** [comment]
I don't think so because, I consider the first one to be 0.

`it doesn't change from frame 0 to frame 3.`

**Comment by nsesh** [comment]
understood. sorry for overlooking :)

**Comment by leandromoreira** [comment]
thanks @nsesh for your review =) it helps a lot!!! I hope this content can help you.

**Comment by nsesh** [comment]
Yes, it is helping me a lot and thanks to you :)
