### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by finallyblueskies** [leandromoreira/digital_video_introduction#95]
Hi guys just wanted to give people a heads up that I've started a [Russian translation](https://github.com/notbogdan/digital_video_introduction/blob/master/README-ru.md) of the document. Anyone feeling like helping out is more than welcome to do so. 

Cheers! B

**Comment by zamanuhina** [comment]
Part 1: https://habr.com/ru/company/edison/blog/481418/
Part 2: https://habr.com/ru/company/edison/blog/480430/
